### ISSUE TITLE
Startup failing due to missing config file

### ISSUE THREAD

**Issue by pdrd** [strangedev/Pynitus#2]
**Env**
Fresh installation on OS-X 10.11.6, Python 3.6.0, Commit 8c8277450a246bdaee325777c031479d6220900c

**Error**
Getting this shortened stacktrace:

> File "/Users/pdrd/Local/src/Pynitus-Backend/Pynitus/__init__.py", line 21, in <module>
> init_config()
> File "/Users/pdrd/Local/src/Pynitus-Backend/Pynitus/io/config.py", line 34, in init_config
> with open(os.path.join("./pynitus.conf")) as f:
> FileNotFoundError: [Errno 2] No such file or directory: './pynitus.conf'

The file does _not_ exist in the directory structure.

**Fix**
Should handle missing file or add default config file.

**Comment by strangedev** [comment]
Missing config file is deliberately not handled, because there are config values without sane defaults.

The error should still be presented in a clearer way, and logged. I've added a TODO for this.

**Comment by pdrd** [comment]
Maybe there should be a hint in the installation instructions? We could add a small comment like 'Edit pynitus.conf to your needs' between:
```
cd Pynitus_Backend
 
# Run the server
```
