### ISSUE TITLE
Missing documentation of required preinstalled software

### ISSUE THREAD

**Issue by pdrd** [strangedev/Pynitus#3]
**Env**
Fresh installation on OS-X 10.11.6, Python 3.6.0, Commit 8c8277450a246bdaee325777c031479d6220900c

**Error**
The actual readme does not contain informations about the required preinstalled system software "memcached" and "taglib". You have to execute memcached before startup. Taglib has to be installed with development headers, otherwise pip cannot build pytaglib dependency.

**Fix**
Do IT :P

**Comment by strangedev** [comment]
Added missing info in 204ae3dc08ab853476db385fc8d40288fc51976f
