### ISSUE TITLE
Bootstrapping sets up virtualenv without specific python version

### ISSUE THREAD

**Issue by pdrd** [strangedev/Pynitus#4]
**Env**
Fresh installation on OS-X 10.11.6, Python 2.7.13, Commit 8c8277450a246bdaee325777c031479d6220900c

**Error**
virtualenv is called in the bootstrap-script without specifying which python version should be used. On my system python2.7 is the default, so virtualenv installs the env with python 2.7. When the script tries to start pynitus following shortened stacktrace occurs:

>   File "/Users/pdrd/Local/src/Pynitus-Backend/.pynitus_venv/lib/python2.7/site-packages/flask/cli.py", line 90, in locate_app
>     __import__(module)
>   File "/Users/pdrd/Local/src/Pynitus-Backend/Pynitus/__init__.py", line 5, in <module>
>     from Pynitus.auth.user_cache import init_user_cache
>   File "/Users/pdrd/Local/src/Pynitus-Backend/Pynitus/auth/user_cache.py", line 34
>     def activity(user_token: str) -> None:
>                            ^
> SyntaxError: invalid syntax

**Fix**
virtualenv can be configured to use a specific python version, e.g. 'virtualenv -p python3 [NAME]'

**Comment by strangedev** [comment]
Fixed in 07838989fbe9a3b010a6d4cb85b0ff6441bee9f8
