### ISSUE TITLE
Improve path handling in bootstrapping

### ISSUE THREAD

**Issue by pdrd** [strangedev/Pynitus#5]
**Environment**
OS-X 10.11.6, Python 3.6.0, Commit 8c8277450a246bdaee325777c031479d6220900c

**Description**
Paths are often set relative, which causes 'NotFound' errors, if you try to execute the bootstrapping script from another directory than the root directory of pynitus.

This might cause problems, if you try to auto-start pynitus on your jukebox server.

**Proposed Action**
Determine the root directory of pynitus (the directory that contains the 'pynitus.sh') and replace the relative directory reference of the paths with the absolute path to the root directory, e.g. './pynitus.conf' => path.join(ROOT, 'pynitus.conf')

**Comment by strangedev** [comment]
As of 3229dd5a0b12f9fdd4ab922ac0315c8593d38042 the bootstrapping script changes it's working directory to the Pynitus root directory.
